import PDFDocument from "pdfkit";

/**
 * Generates a clean, modern PDF document for a Monthly Financial Report.
 *
 * @param {Object} reportData - Report data object from MonthlyReport document
 * @param {Object} user - User object containing name, email, etc.
 * @param {string} reportMonthLabel - e.g., "July 2026"
 * @returns {PDFDocument} - PDFKit document instance (readable stream)
 */
export const generateMonthlyReportPDF = (reportData, user, reportMonthLabel = "") => {
  const doc = new PDFDocument({
    size: "A4",
    margin: 40,
    bufferPages: true,
  });

  const data = reportData?.data || {};
  const summary = data.summary || {};
  const categoryBreakdown = data.categoryBreakdown || [];
  const budgetPerf = data.budgetPerformance || {};
  const healthScore = data.healthScore || {};
  const aiRecs = data.aiRecommendations || {};
  const spendingTrends = data.spendingTrends || {};

  // Palette
  const PRIMARY_DARK = "#0f172a";
  const PRIMARY_INDIGO = "#6366f1";
  const ACCENT_EMERALD = "#10b981";
  const ACCENT_ROSE = "#f43f5e";
  const ACCENT_AMBER = "#f59e0b";
  const BG_LIGHT = "#f8fafc";
  const CARD_BG = "#f1f5f9";
  const TEXT_DARK = "#1e293b";
  const TEXT_MUTED = "#64748b";
  const BORDER_COLOR = "#e2e8f0";

  const pageWidth = doc.page.width - 80; // 595.28 - 80 = 515.28

  // Helper for drawing rounded boxes
  const drawCard = (x, y, w, h, bg = CARD_BG, border = BORDER_COLOR) => {
    doc.save();
    doc.roundedRect(x, y, w, h, 8).fillAndStroke(bg, border);
    doc.restore();
  };

  // Helper for Section Headers
  const drawSectionHeader = (title, y) => {
    doc.save();
    doc.fontSize(14).font("Helvetica-Bold").fillColor(PRIMARY_DARK).text(title, 40, y);
    doc.moveTo(40, y + 18).lineTo(40 + pageWidth, y + 18).strokeColor(PRIMARY_INDIGO).lineWidth(2).stroke();
    doc.restore();
    return y + 26;
  };

  // ─── Header & Branding ──────────────────────────────────────────────────
  // Top Banner Bar
  doc.rect(40, 40, pageWidth, 60).fill(PRIMARY_DARK);

  // Logo Box
  doc.roundedRect(52, 50, 40, 40, 6).fill(PRIMARY_INDIGO);
  doc.fontSize(18).font("Helvetica-Bold").fillColor("#ffffff").text("SS", 62, 60);

  // Title & Subtitle
  doc.fontSize(16).font("Helvetica-Bold").fillColor("#ffffff").text("SpendSense AI", 102, 52);
  doc.fontSize(10).font("Helvetica").fillColor("#94a3b8").text("AI Monthly Financial Report", 102, 72);

  // User Info Block (Right aligned)
  doc.fontSize(9).font("Helvetica-Bold").fillColor("#ffffff").text(user?.name || "Valued User", 340, 52, { width: 200, align: "right" });
  doc.fontSize(8).font("Helvetica").fillColor("#cbd5e1").text(user?.email || "", 340, 65, { width: 200, align: "right" });
  doc.fontSize(8).font("Helvetica").fillColor("#94a3b8").text(`Period: ${reportMonthLabel || data.reportMonthLabel || "Monthly"}`, 340, 77, { width: 200, align: "right" });

  let curY = 115;

  // ─── Executive Summary ──────────────────────────────────────────────────
  drawCard(40, curY, pageWidth, 65, BG_LIGHT, PRIMARY_INDIGO);
  doc.fontSize(10).font("Helvetica-Bold").fillColor(PRIMARY_INDIGO).text("EXECUTIVE OVERVIEW", 52, curY + 10);
  doc.fontSize(9).font("Helvetica").fillColor(TEXT_DARK).text(
    summary.overview || "Monthly financial report generated by SpendSense AI.",
    52,
    curY + 24,
    { width: pageWidth - 24, height: 34, ellipsis: true }
  );

  curY += 75;

  // ─── Core Metrics Grid ──────────────────────────────────────────────────
  curY = drawSectionHeader("Monthly Financial Summary", curY);

  const cardW = (pageWidth - 30) / 4;
  const cardsData = [
    { label: "Monthly Income", val: `Rs. ${(summary.totalIncome || 0).toLocaleString()}`, color: PRIMARY_DARK },
    { label: "Total Expenses", val: `Rs. ${(summary.totalExpenses || 0).toLocaleString()}`, color: ACCENT_ROSE },
    { label: "Net Savings", val: `Rs. ${(summary.netSavings || 0).toLocaleString()}`, color: ACCENT_EMERALD },
    { label: "Savings Rate", val: `${(summary.savingsRate || 0).toFixed(1)}%`, color: PRIMARY_INDIGO },
  ];

  cardsData.forEach((c, idx) => {
    const cx = 40 + idx * (cardW + 10);
    drawCard(cx, curY, cardW, 48, CARD_BG, BORDER_COLOR);
    doc.fontSize(8).font("Helvetica-Bold").fillColor(TEXT_MUTED).text(c.label.toUpperCase(), cx + 8, curY + 8);
    doc.fontSize(11).font("Helvetica-Bold").fillColor(c.color).text(c.val, cx + 8, curY + 24, { width: cardW - 16, ellipsis: true });
  });

  curY += 60;

  // ─── Financial Health Score & Budget Summary ───────────────────────────
  curY = drawSectionHeader("Financial Health & Budget Performance", curY);

  const halfW = (pageWidth - 15) / 2;

  // Health Score Box
  drawCard(40, curY, halfW, 90, BG_LIGHT, BORDER_COLOR);
  doc.fontSize(11).font("Helvetica-Bold").fillColor(PRIMARY_DARK).text("Financial Health Score", 52, curY + 10);
  doc.fontSize(22).font("Helvetica-Bold").fillColor(PRIMARY_INDIGO).text(`${healthScore.score || 0}`, 52, curY + 26);
  doc.fontSize(10).font("Helvetica").fillColor(TEXT_MUTED).text("/ 100", 90, curY + 36);

  doc.fontSize(10).font("Helvetica-Bold").fillColor(ACCENT_EMERALD).text(`Grade: ${healthScore.grade || "N/A"}`, 140, curY + 32);

  doc.fontSize(8).font("Helvetica").fillColor(TEXT_DARK).text(
    healthScore.summary || "Holistic health score derived from savings rate, consistency, and budget adherence.",
    52,
    curY + 54,
    { width: halfW - 24, height: 30, ellipsis: true }
  );

  // Budget Performance Box
  drawCard(40 + halfW + 15, curY, halfW, 90, BG_LIGHT, BORDER_COLOR);
  doc.fontSize(11).font("Helvetica-Bold").fillColor(PRIMARY_DARK).text("Budget Performance", 40 + halfW + 27, curY + 10);
  doc.fontSize(22).font("Helvetica-Bold").fillColor(ACCENT_AMBER).text(`Grade ${budgetPerf.grade || "N/A"}`, 40 + halfW + 27, curY + 26);

  doc.fontSize(8).font("Helvetica-Bold").fillColor(TEXT_MUTED).text(
    `Target: Rs. ${(budgetPerf.totalBudget || 0).toLocaleString()} | Spent: Rs. ${(budgetPerf.totalSpent || 0).toLocaleString()}`,
    40 + halfW + 27,
    curY + 52
  );
  doc.fontSize(8).font("Helvetica").fillColor(TEXT_DARK).text(
    `Variance: Rs. ${(budgetPerf.variance || 0).toLocaleString()}`,
    40 + halfW + 27,
    curY + 66
  );

  curY += 105;

  // ─── Highest & Lowest Expense Spotlight ───────────────────────────────
  curY = drawSectionHeader("Expense Spotlight", curY);

  // Highest Expense Box
  drawCard(40, curY, halfW, 55, CARD_BG, ACCENT_ROSE);
  doc.fontSize(8).font("Helvetica-Bold").fillColor(ACCENT_ROSE).text("HIGHEST EXPENSE", 52, curY + 8);
  doc.fontSize(11).font("Helvetica-Bold").fillColor(TEXT_DARK).text(
    `Rs. ${(summary.highestExpense?.amount || 0).toLocaleString()} - ${summary.highestExpense?.title || "N/A"}`,
    52,
    curY + 22,
    { width: halfW - 24, ellipsis: true }
  );
  doc.fontSize(8).font("Helvetica").fillColor(TEXT_MUTED).text(
    `Category: ${summary.highestExpense?.category || "N/A"}`,
    52,
    curY + 38
  );

  // Lowest Expense Box
  drawCard(40 + halfW + 15, curY, halfW, 55, CARD_BG, ACCENT_EMERALD);
  doc.fontSize(8).font("Helvetica-Bold").fillColor(ACCENT_EMERALD).text("LOWEST EXPENSE", 40 + halfW + 27, curY + 8);
  doc.fontSize(11).font("Helvetica-Bold").fillColor(TEXT_DARK).text(
    `Rs. ${(summary.lowestExpense?.amount || 0).toLocaleString()} - ${summary.lowestExpense?.title || "N/A"}`,
    40 + halfW + 27,
    curY + 22,
    { width: halfW - 24, ellipsis: true }
  );
  doc.fontSize(8).font("Helvetica").fillColor(TEXT_MUTED).text(
    `Category: ${summary.lowestExpense?.category || "N/A"}`,
    40 + halfW + 27,
    curY + 38
  );

  curY += 70;

  // ─── Category Breakdown Table ──────────────────────────────────────────
  curY = drawSectionHeader("Category-wise Spending Breakdown", curY);

  // Table Header Bar
  doc.rect(40, curY, pageWidth, 20).fill(PRIMARY_DARK);
  doc.fontSize(8).font("Helvetica-Bold").fillColor("#ffffff");
  doc.text("CATEGORY", 48, curY + 6);
  doc.text("TOTAL (Rs.)", 180, curY + 6, { width: 80, align: "right" });
  doc.text("SHARE", 280, curY + 6, { width: 50, align: "right" });
  doc.text("COUNT", 355, curY + 6, { width: 45, align: "right" });
  doc.text("AI INSIGHT & RECOMMENDATION", 415, curY + 6);

  curY += 20;

  const rowH = 22;
  const maxRows = Math.min(categoryBreakdown.length, 6);

  for (let i = 0; i < maxRows; i++) {
    const cat = categoryBreakdown[i];
    const bg = i % 2 === 0 ? "#ffffff" : BG_LIGHT;
    doc.rect(40, curY, pageWidth, rowH).fillAndStroke(bg, BORDER_COLOR);

    doc.fontSize(8).font("Helvetica-Bold").fillColor(TEXT_DARK).text(cat.category || "General", 48, curY + 6, { width: 120, ellipsis: true });
    doc.fontSize(8).font("Helvetica").fillColor(TEXT_DARK).text((cat.total || 0).toLocaleString(), 180, curY + 6, { width: 80, align: "right" });
    doc.fontSize(8).font("Helvetica").fillColor(PRIMARY_INDIGO).text(`${cat.percentage || 0}%`, 280, curY + 6, { width: 50, align: "right" });
    doc.fontSize(8).font("Helvetica").fillColor(TEXT_MUTED).text(`${cat.count || 0}`, 355, curY + 6, { width: 45, align: "right" });

    const insightText = cat.recommendation || cat.insight || "Monitor spending in this category.";
    doc.fontSize(7.5).font("Helvetica").fillColor(TEXT_MUTED).text(insightText, 415, curY + 6, { width: 130, height: 14, ellipsis: true });

    curY += rowH;
  }

  curY += 15;

  // Check if we need a new page for Recommendations & Savings Tips
  if (curY > 650) {
    doc.addPage();
    curY = 40;
  }

  // ─── AI Recommendations & Savings Tips ────────────────────────────────
  curY = drawSectionHeader("AI Strategic Recommendations & Savings Tips", curY);

  // Top Immediate Actions
  if (aiRecs.immediateActions && aiRecs.immediateActions.length > 0) {
    doc.fontSize(9).font("Helvetica-Bold").fillColor(PRIMARY_DARK).text("TOP PRIORITY IMMEDIATE ACTIONS", 40, curY);
    curY += 14;

    aiRecs.immediateActions.slice(0, 3).forEach((act) => {
      drawCard(40, curY, pageWidth, 24, BG_LIGHT, BORDER_COLOR);
      doc.fontSize(8).font("Helvetica-Bold").fillColor(PRIMARY_INDIGO).text(`#${act.rank}`, 48, curY + 7);
      doc.fontSize(8).font("Helvetica-Bold").fillColor(TEXT_DARK).text(act.action || "", 70, curY + 7, { width: 330, ellipsis: true });
      if (act.estimatedSaving > 0) {
        doc.fontSize(8).font("Helvetica-Bold").fillColor(ACCENT_EMERALD).text(`Est. Saving: Rs. ${act.estimatedSaving.toLocaleString()}`, 400, curY + 7, { width: 145, align: "right" });
      }
      curY += 28;
    });
  }

  // Savings Opportunities & Tips
  if (aiRecs.savingsOpportunities && aiRecs.savingsOpportunities.length > 0) {
    curY += 5;
    doc.fontSize(9).font("Helvetica-Bold").fillColor(PRIMARY_DARK).text("IDENTIFIED SAVINGS OPPORTUNITIES", 40, curY);
    curY += 14;

    aiRecs.savingsOpportunities.slice(0, 2).forEach((opp) => {
      drawCard(40, curY, pageWidth, 32, BG_LIGHT, BORDER_COLOR);
      doc.fontSize(8.5).font("Helvetica-Bold").fillColor(TEXT_DARK).text(opp.title || "Savings Tip", 48, curY + 6);
      doc.fontSize(7.5).font("Helvetica").fillColor(TEXT_MUTED).text(opp.description || "", 48, curY + 18, { width: pageWidth - 20, height: 10, ellipsis: true });
      curY += 36;
    });
  }

  // Next Month Goals
  if (aiRecs.nextMonthGoals && aiRecs.nextMonthGoals.length > 0) {
    curY += 5;
    doc.fontSize(9).font("Helvetica-Bold").fillColor(PRIMARY_DARK).text("ACTIONABLE GOALS FOR NEXT MONTH", 40, curY);
    curY += 14;

    const goalW = (pageWidth - 20) / 3;
    aiRecs.nextMonthGoals.slice(0, 3).forEach((goal, idx) => {
      const gx = 40 + idx * (goalW + 10);
      drawCard(gx, curY, goalW, 30, CARD_BG, BORDER_COLOR);
      doc.fontSize(8).font("Helvetica-Bold").fillColor(ACCENT_AMBER).text(`Goal ${idx + 1}`, gx + 8, curY + 5);
      doc.fontSize(7.5).font("Helvetica").fillColor(TEXT_DARK).text(goal, gx + 8, curY + 16, { width: goalW - 16, height: 12, ellipsis: true });
    });
  }

  // ─── Footer Page Numbering ───────────────────────────────────────────────
  const pages = doc.bufferedPageRange();
  for (let i = 0; i < pages.count; i++) {
    doc.switchToPage(i);
    doc.fontSize(8).font("Helvetica").fillColor(TEXT_MUTED).text(
      `SpendSense AI Financial Report • Generated on ${new Date().toLocaleDateString()} • Page ${i + 1} of ${pages.count}`,
      40,
      doc.page.height - 30,
      { width: pageWidth, align: "center" }
    );
  }

  return doc;
};
